### ISSUE TITLE
US 01.01.01 - As a meal planner, I want to add an ingredient, with a brief description, best before date, location, amount, unit, and ingredient category so I can keep track of my pantry.

### ISSUE THREAD

**Issue by kwiskel** [CMPUT301F22T12/CMPUT301Project#1]

**Comment by phillipkluge** [comment]
# Acceptance Criteria
- Window to add criteria has space for the name, description, best before date, location, amount, unit, and category.
- Hitting the "finish" or "done" button places the completed fields into the food list
