### ISSUE TITLE
US 02.05.01 - As a meal planner, I want to edit the details of a recipe, including the ingredients so I can make changes to my recipes.

### ISSUE THREAD

**Issue by kwiskel** [CMPUT301F22T12/CMPUT301Project#11]

**Comment by phillipkluge** [comment]
# Acceptance Criteria
- Tapping on a recipe in the list will bring up the edit menu
- Fields inside the edit menu will be auto filled with the existing parameters
- Tapping the "done" button will update the recipe's parameters with the new input
- Any unchanged fields will remain the same in the list
