### ISSUE TITLE
US 02.07.01 - As a meal planner, I want to see a list of my recipes so I can keep track of recipes I have already made and still need to make

### ISSUE THREAD

**Issue by kwiskel** [CMPUT301F22T12/CMPUT301Project#13]

**Comment by phillipkluge** [comment]
# Acceptance Criteria
- All recipes will be displayed in a vertical list
- The added recipes will have information displayed about their name, prep time, servings, category, as well as a photo
- The optionally included photo will be displayed with the recipe's details in a small thumbnail size
- The recipes can be sorted by their parameters (excluding the photo)
