### ISSUE TITLE
US 03.01.01 - As a meal planner, I want to make a meal plan, for several upcoming days of meals, based on choosing from my recipes or individually from my ingredient storage so I can plan what to eat several meals in advance

### ISSUE THREAD

**Issue by kwiskel** [CMPUT301F22T12/CMPUT301Project#15]

**Comment by phillipkluge** [comment]
# Acceptance Criteria
- Choosing "plan meal" from the meals menu will pop up a submenu to fill in the meal plan's details
- The name, instructions, details, as well as the planned day can be filled in
- When creating a meal plan from scratch, the fields to enter its details will be blank
- Recipes and ingredients can be chosen from the recipe and ingredient list respectively
   - Any attached recipe/ingredient is able to be viewed when viewing the meal plan's details
