### ISSUE TITLE
US 03.02.01 - As a meal planner, I want to scale my recipes to adjust the number of servings for the meal plan so I can account for guests or myself.

### ISSUE THREAD

**Issue by kwiskel** [CMPUT301F22T12/CMPUT301Project#16]

**Comment by phillipkluge** [comment]
# Acceptance Criteria
- Tapping on a meal plan will bring up a submenu to edit its details
- From the edit submenu, the number of servings for that meal plan can be adjusted
- The number of servings should accept non-integer values
- Any associated meals will have the number of ingredients multiplied by the number of servings

**Comment by antarc0y** [comment]
- user can also add more than one recipe to one meal
- Ex: meal 'waffle and eggs' can contain 2 recipes, for waffles and for eggs separately
- user can also add extra individual ingredients from inventory that is not part of the selected recipe, like add cherries on top of waffles to tailor to personal preferences
