### ISSUE TITLE
US 04.01.01 - As a meal planner, I want to view a shopping list of ingredients that I need to buy, based on my ingredient storage and meal plan so that I can make sure I have all ingredients necessary to complete my meal plan

### ISSUE THREAD

**Issue by kwiskel** [CMPUT301F22T12/CMPUT301Project#17]

**Comment by phillipkluge** [comment]
# Acceptance Criteria
- Tapping on the "shopping" tab will bring up a list of ingredients to buy
- The ingredients are taken from any active meal plans and associated recipes
- The number of ingredients to buy are based on the the ingredient requirement for each recipe and how many ingredients are already in storage
   - If there are fewer ingredients in storage than are needed for the meal plan, the difference in the number of ingredients will be added to the shopping list
 - The meal planner can manually add or remove ingredients in the shopping list
