### ISSUE TITLE
US 04.02.01 - As a meal planner, I want each ingredient on the shopping list to show its description, amount, unit, and ingredient category so that I know how much I will spend on ingredients

### ISSUE THREAD

**Issue by kwiskel** [CMPUT301F22T12/CMPUT301Project#18]

**Comment by phillipkluge** [comment]
# Acceptance Criteria
- All shopping ingredients are displayed in a vertical list
- The added ingredients will have information displayed about their description, amount, unit, and category
- The ingredients can be sorted by their details (name, amount etc.)
