### ISSUE TITLE
US 04.03.01 - As a meal planner, I want to sort the shopping list of ingredients by description or category so I can find what I need to buy.

### ISSUE THREAD

**Issue by kwiskel** [CMPUT301F22T12/CMPUT301Project#19]

**Comment by phillipkluge** [comment]
#Acceptance Criteria
- Tapping on one of the "sort by" buttons will sort the list by that parameter
- Tapping on the "sort" button again will sort the list by that category in reverse order
- Text parameters like the category or description will be sorted in alphabetical/reverse alphabetical order
- Numerical parameters like the amount will be sorted by numerical/reverse numerical order
