### ISSUE TITLE
US 04.05.01 - As a meal planner, I want to add ingredients I have picked up to my ingredient storage, reminding me to complete details like location, actual amount, and unit so that I can use them

### ISSUE THREAD

**Issue by kwiskel** [CMPUT301F22T12/CMPUT301Project#21]

**Comment by phillipkluge** [comment]
# Acceptance Criteria
- Swiping left on an ingredient in the shopping list marks it as picked up
- When an ingredient is marked as picked up and added to the ingredient list, it is highlighted in red to remind the meal planner to complete the addition of its details including location, amount, unit etc.
   - Basic parameters are auto filled including the amount (based on the shopping list amount)

**Comment by phillipkluge** [comment]
# Acceptance Criteria
- Swiping left on an ingredient in the shopping list marks it as picked up
- When an ingredient is marked as picked up and added to the ingredient list, it is highlighted in red to remind the meal planner to complete the addition of its details including location, amount, unit etc.
   - Basic parameters are auto filled including the amount (based on the shopping list amount)
