### ISSUE TITLE
US 01.03.01 - As a meal planner, I want to edit the details of an ingredient so that I can update changes to the ingredient.

### ISSUE THREAD

**Issue by kwiskel** [CMPUT301F22T12/CMPUT301Project#3]

**Comment by phillipkluge** [comment]
# Acceptance Criteria
- Tapping on a food in the list will bring up the edit menu
- Fields inside the edit menu will be auto filled with the existing parameters
- Tapping the "done" button will update the food's parameters with the new input
   - Any unchanged fields will remain the same in the list
