### ISSUE TITLE
US 01.04.01 - As a meal planner, I want to delete an ingredient so that I can remove it when it is gone.

### ISSUE THREAD

**Issue by kwiskel** [CMPUT301F22T12/CMPUT301Project#4]

**Comment by phillipkluge** [comment]
# Acceptance Criteria
- Swiping right on a food in the ingredients list will remove it
- Associated ingredient in a recipe will also be removed

**Comment by antarc0y** [comment]
- confirm deletion button will pop up after swipe to prevent accidental deletions
