### ISSUE TITLE
US 01.05.01 - As a meal planner, I want to see a list of my ingredients so I can see what I have to work with

### ISSUE THREAD

**Issue by kwiskel** [CMPUT301F22T12/CMPUT301Project#5]

**Comment by phillipkluge** [comment]
# Acceptance Criteria
- All added ingredients will be displayed in a vertical list
- The added ingredients will have information displayed about their name, expiry date, location, category, and amount in a tabular format
- The ingredients can be sorted by their details (name, expiry date etc.)
