### ISSUE TITLE
US 01.06.01 - As a meal planner, I want to sort the list of ingredients by description, best before date, location, and ingredient category so I can tell what kind of foods I have.

### ISSUE THREAD

**Issue by kwiskel** [CMPUT301F22T12/CMPUT301Project#6]

**Comment by phillipkluge** [comment]
# Acceptance Criteria
- Tapping on one of the "sort by" buttons will sort the list by that parameter
- Tapping on the "sort" button again will sort the list by that category in reverse order
- Text parameters like name, location, or category will be displayed in alphabetical/reverse alphabetical order
- Numerical parameters like the best before/expiry date will be done in numerical/reverse numerical order

**Comment by antarc0y** [comment]
- the sort by button will create a drop down list where user can select which parameter to sort by
- sort by expiry date will put the nearest expiry date first
- expired items will be highlighted in red
