### ISSUE TITLE
US 01.01.02 - As a meal planner, I want to add a photograph to an Ingredient so I can keep track of my Storage

### ISSUE THREAD

**Issue by kwiskel** [CMPUT301F22T12/CMPUT301Project#64]
### Acceptance Criteria
- A photograph of the ingredient can be uploaded when adding an ingredient or editing an ingredient.
- Photograph can be viewed when viewing details of an ingredient

**Comment by yismailuofa** [comment]
Is this correct, did you mean Recipe?
