### ISSUE TITLE
US 02.01.01 - As a meal planner, I want to add a recipe, with title, preparation time, number of servings, recipe category, comments, and list of ingredients so I can prepare them in the future.

### ISSUE THREAD

**Issue by kwiskel** [CMPUT301F22T12/CMPUT301Project#7]

**Comment by phillipkluge** [comment]
# Acceptance Criteria
- From the recipe list view, tapping "add recipe" will bring up a submenu to fill in recipe details
- Empty text boxes to fill in the recipe's name, preparation time, number of servings, category, and comments will be displayed
- A photograph of the completed recipe can be uploaded in the same submenu
- A meal planner can choose a list of ingredients from their total ingredient list

**Comment by phillipkluge** [comment]
# Acceptance Criteria
- From the recipe list view, tapping "add recipe" will bring up a submenu to fill in recipe details
- Empty text boxes to fill in the recipe's name, preparation time, number of servings, category, and comments will be displayed
- A photograph of the completed recipe can be uploaded in the same submenu
- A meal planner can choose a list of ingredients from their total ingredient list
