### ISSUE TITLE
US 02.02.01 - As a meal planner, I want to add an ingredient to a recipe, with a brief description, amount, unit, and ingredient category so I can add ingredients if I need it for a recipe.

### ISSUE THREAD

**Issue by kwiskel** [CMPUT301F22T12/CMPUT301Project#8]

**Comment by phillipkluge** [comment]
# Acceptance Criteria
- When creating or editing a recipe, the option to add ingredients will be displayed in the create/edit recipe submenu
- Ingredients can be chosen from the ingredients list
- The addition of a description, amount, unit, and category can be included for each ingredient
- All ingredients associated with a recipe will be displayed in that recipe's details
